// "New Project" step 0: turn a few answers into a skeleton board.yml.
//
// board.yml is the project contract (the single source of truth the CLI scaffolds
// from). This builds a *valid skeleton* — meta is correct and complete, extras are
// included when asked — that always passes `mcuflow validate`. Pin numbers are only
// asserted for the esp32c3 (the board we can speak to confidently); for other chips
// they're left as VERIFY comments for the "Refine with Agent" pass to fill in.
//
// Schema constraints respected (src/board-schema/board.schema.json):
//   meta.required = [project, platform, chip]; platform ∈ esp32|stm32|rp2040|zephyr
//   devices.<n>.required = [part, bus]; address is an integer; no extra keys
//   test = {needs[], boot_string}; rig = {dut_reset_gpio, dut_boot_gpio, satellite}

export interface DeviceSpec {
  name: string; // the board.yml device key (e.g. "temp")
  part: string;
  bus: string;
  address?: string; // YAML hex literal, parsed as int (e.g. "0x76")
  driver?: string;
  desc: string; // for the QuickPick
}

/** Curated, honest catalog — only parts we can spec correctly. */
export const DEVICE_CATALOG: Record<string, DeviceSpec> = {
  bme280: {
    name: "temp",
    part: "BME280",
    bus: "i2c0",
    address: "0x76",
    driver: "espressif/bme280",
    desc: "BME280 — temperature / humidity (I²C)",
  },
};

export const CHIPS = ["esp32c3", "esp32", "esp32s3", "esp32c6"];

// Dropped into a new project's .vscode/ by New Project; on the next activation
// (after the folder opens) it triggers the Configure step, then is deleted.
export const CONFIGURE_MARKER = ".mcuflow-configure";

/** Validate the New Project form. Returns an error string, or null if OK. */
export function validateNewProject(name: string, location: string): string | null {
  if (!location.trim()) {
    return "Choose a location.";
  }
  if (!name.trim()) {
    return "Enter a project name.";
  }
  if (!/^[A-Za-z0-9._-]+$/.test(name.trim())) {
    return "Name: use only letters, digits, dot, dash, underscore.";
  }
  return null;
}

export interface NewProjectOpts {
  project: string;
  chip: string;
  devices: string[]; // keys into DEVICE_CATALOG
  needs: string[]; // subset of ["serial", "wifi"]
}

export function buildBoardYaml(opts: NewProjectOpts): string {
  const specs = opts.devices.map((k) => DEVICE_CATALOG[k]).filter(Boolean);
  const needs = opts.needs;
  const wifi = needs.includes("wifi");

  // Only what's required by the schema (meta) plus what the user actually chose
  // (devices, test needs, satellite). No assumed defaults - no flash size, CPU
  // freq, sleep mode, guessed LED/BOOT pins, or boot string. Configure / Refine
  // with Agent fill the rest.
  const L: string[] = [];
  L.push("# board.yml — generated by MCU Flow.");
  L.push("# Fill in pins, and refine devices/tests with Configure or the agent.");
  L.push("meta:");
  L.push(`  project: ${opts.project}`);
  L.push("  platform: esp32");
  L.push(`  chip: ${opts.chip}`);

  // A device's bus must be declared under pins (the validator cross-checks it).
  // Declare each bus as an empty map so the file stays valid without guessing
  // pin numbers - the agent/Configure fills sda/scl etc.
  const buses = Array.from(new Set(specs.map((d) => d.bus)));
  if (buses.length) {
    L.push("");
    L.push("pins:");
    for (const b of buses) {
      L.push(`  ${b}: {}   # set the pins for ${b}`);
    }
  }

  if (specs.length) {
    L.push("");
    L.push("devices:");
    for (const d of specs) {
      const parts = [`part: ${d.part}`, `bus: ${d.bus}`];
      if (d.address) {
        parts.push(`address: ${d.address}`);
      }
      if (d.driver) {
        parts.push(`driver: ${d.driver}`);
      }
      L.push(`  ${d.name}: { ${parts.join(", ")} }`);
    }
  }

  if (needs.length) {
    L.push("");
    L.push("test:");
    L.push(`  needs: [${needs.join(", ")}]`);
  }

  if (wifi) {
    L.push("");
    L.push("rig:");
    L.push("  satellite: required");
  }

  L.push("");
  return L.join("\n");
}
