// "New Project" step 0: turn a few answers into a skeleton board.yml.
//
// board.yml is the project contract (the single source of truth the CLI scaffolds
// from). This builds a *valid skeleton* — meta is correct and complete, extras are
// included when asked — that always passes `mcuflow validate`. Pin numbers are only
// asserted for the esp32c3 (the board we can speak to confidently); for other chips
// they're left as VERIFY comments for the "Refine with Agent" pass to fill in.
//
// Schema constraints respected (src/board-schema/board.schema.json):
//   meta.required = [project, platform, chip]; platform ∈ esp32|stm32|rp2040|zephyr
//   devices.<n>.required = [part, bus]; address is an integer; no extra keys
//   test = {needs[], boot_string}; rig = {dut_reset_gpio, dut_boot_gpio, satellite}

export interface DeviceSpec {
  name: string; // the board.yml device key (e.g. "temp")
  part: string;
  bus: string;
  address?: string; // YAML hex literal, parsed as int (e.g. "0x76")
  driver?: string;
  desc: string; // for the QuickPick
}

/** Curated, honest catalog — only parts we can spec correctly. */
export const DEVICE_CATALOG: Record<string, DeviceSpec> = {
  bme280: {
    name: "temp",
    part: "BME280",
    bus: "i2c0",
    address: "0x76",
    driver: "espressif/bme280",
    desc: "BME280 — temperature / humidity (I²C)",
  },
};

export const CHIPS = ["esp32c3", "esp32", "esp32s3", "esp32c6"];

// Dropped into a new project's .vscode/ by New Project; on the next activation
// (after the folder opens) it triggers the Configure step, then is deleted.
export const CONFIGURE_MARKER = ".mcuflow-configure";

/** Validate the New Project form. Returns an error string, or null if OK. */
export function validateNewProject(name: string, location: string): string | null {
  if (!location.trim()) {
    return "Choose a location.";
  }
  if (!name.trim()) {
    return "Enter a project name.";
  }
  if (!/^[A-Za-z0-9._-]+$/.test(name.trim())) {
    return "Name: use only letters, digits, dot, dash, underscore.";
  }
  return null;
}

export interface NewProjectOpts {
  project: string;
  chip: string;
  devices: string[]; // keys into DEVICE_CATALOG
  needs: string[]; // subset of ["serial", "wifi"]
}

export function buildBoardYaml(opts: NewProjectOpts): string {
  const isC3 = opts.chip === "esp32c3";
  const specs = opts.devices.map((k) => DEVICE_CATALOG[k]).filter(Boolean);
  const usesI2c = specs.some((d) => d.bus.startsWith("i2c"));
  const needs = opts.needs.length ? opts.needs : ["serial"];
  const wifi = needs.includes("wifi");

  const L: string[] = [];
  L.push('# board.yml — generated by MCU Flow "New Project".');
  L.push("# A SKELETON: meta is complete; verify pins for your exact board and");
  L.push('# refine devices/tests with the agent ("Refine with Agent") before');
  L.push("# scaffolding. Run `mcuflow validate board.yml` after edits.");
  L.push("meta:");
  L.push(`  project: ${opts.project}`);
  L.push("  platform: esp32          # the esp32 adapter (covers C3/S3/C6)");
  L.push(`  chip: ${opts.chip}`);
  L.push(`  board: ${opts.chip}`);
  L.push("  framework: esp-idf");
  L.push("");
  L.push("build:");
  L.push("  sdkconfig:");
  L.push("    CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y");
  L.push("    CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG: y   # console over the native USB");
  L.push("");
  // pins: any bus a device sits on MUST be defined here (the validator
  // cross-checks device.bus against pins). We emit those buses with sensible
  // defaults (+ a VERIFY note for non-C3 chips). status_led isn't required by
  // anything, so it's a concrete value on the C3 and a guidance comment
  // elsewhere. An empty `pins:` mapping parses as null and fails the schema, so
  // when there's nothing concrete we omit the key (it's optional).
  const pinLines: string[] = [];
  const pinComments: string[] = [];
  if (isC3) {
    pinLines.push("  status_led: 8            # C3 Super Mini onboard LED (active-low)");
  } else {
    pinComments.push(`  # status_led: <pin>     # VERIFY: onboard LED pin for ${opts.chip}`);
  }
  if (usesI2c) {
    const note = isC3 ? "clear of LED/BOOT/UART" : `VERIFY pins for ${opts.chip}`;
    pinLines.push(`  i2c0: { sda: 5, scl: 6, freq_hz: 400000 }   # ${note}`);
  }
  if (pinLines.length) {
    L.push("pins:");
    L.push(...pinComments, ...pinLines);
  } else if (pinComments.length) {
    // nothing concrete and no device bus to define - leave guidance only
    L.push(...pinComments.map((c) => c.replace(/^ {2}/, "")));
  }
  L.push("");

  if (specs.length) {
    L.push("devices:");
    for (const d of specs) {
      const parts = [`part: ${d.part}`, `bus: ${d.bus}`];
      if (d.address) {
        parts.push(`address: ${d.address}`);
      }
      if (d.driver) {
        parts.push(`driver: ${d.driver}`);
      }
      L.push(`  ${d.name}: { ${parts.join(", ")} }`);
    }
    L.push("");
  }

  L.push("power:");
  L.push("  sleep: none");
  L.push("  cpu_freq_mhz: 160");
  L.push("");
  L.push("test:");
  L.push(`  needs: [${needs.join(", ")}]`);
  L.push('  boot_string: "app_main started"');
  L.push("");
  L.push("rig:");
  if (isC3) {
    L.push("  dut_boot_gpio: 9         # satellite drives this to force download mode");
  } else {
    L.push(`  # dut_boot_gpio: <pin>   # VERIFY: BOOT strap pin for ${opts.chip}`);
  }
  L.push(`  satellite: ${wifi ? "required" : "optional"}${wifi ? "      # the wifi test needs the satellite board" : ""}`);
  L.push("");
  return L.join("\n");
}
